# when using the default proxy server port
# local_backend: true

backend:
  name: git-gateway
  api_root: https://api.github.com
  repo: delasmanos/gnublog
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://delasmanos.github.io/gnublog/"

collections:
  - name: blog
    label: Articles
    folder: src/content/blog
    create: true
    extension: mdx
    format: frontmatter
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: subTitle, label: Subtitle }
      - { name: description, label: Description }
      - { name: pubDate, label: Date, widget: datetime, date_format: "YYYY-MM-DD" }
      # eventuel auf absoluten path umschwenken wenn das nochmal passiert das bild nicht den pfad hat : /src/content/blog
      - { name: heroImage, label: Hero image, widget: image, allow_multiple: false, media_folder: './'  }
      - { name: heroImageAltText, label: Hero image alt text }
      - { name: showHeadingPermalink, label: Show Permalinks in headings, widget: "boolean" , default: false}
      - { name: showToc, label: Show Table of contents, widget: "boolean" , default: false}
      - { name: published, label: Mark as published,  widget: "boolean" , default: false}
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Denio", value: "delasmanos" }
          - { label: "Christoph", value: "christoph" }
          - { label: "Daniel Funki Funk", value: "daniel" }
          - { label: "Benno", value: "benno" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        options:
          - { label: "article", value: "article" }
          - { label: "music-production", value: "music-production" }
          - { label: "coding", value: "coding" }

  - name: band-mates
    label: bandmates
    folder: src/content/band-mates
    create: true
    extension: md
    format: frontmatter
    preview_path: band-mates/{{id}}
    fields:
      - { name: name, label: Name, widget: "string" }
      - { name: nickName, label: Nickname, widget: "string" }
      - { name: postion, label: postion, widget: "string" }
      - { name: avatar, label: Avatar, widget: image, allow_multiple: false, media_folder: './'  }
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }

  - name: settings
    label: Site settings
    folder: src/content/settings
    create: false
    extension: json
    format: frontmatter
    preview_path: settings/{{id}}
    fields:
      - { name: siteName, label: Site name, widget: "string" }
      - { name: siteDescription, label: Site description, widget: "string" }
      - { name: domain, label: postion, widget: "string" }
      - { name: brandSlogan, label: Brand slogan, widget: string }
      - { name: email, label: Brand slogan, widget: string }
      - label: 'Telephone'
        name: 'telephone'
        widget: 'object'
        collapsed: false
        fields:
          - { name: prefix, label: Telphone prefix, widget: "string" }
          - { name: number, label: Telphone number, widget: "string" }
  