backend:
  name: git-gateway
  api_root: https://api.github.com
  repo: delasmanos/gnublog
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://delasmanos.github.io/gnublog/"

collections:
  - name: blog
    label: Articles
    folder: src/content/blog
    create: true
    extension: mdx
    format: frontmatter
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: subTitle, label: Subtitle }
      - { name: description, label: Description }
      - { name: pubDate, label: Date, widget: datetime, date_format: "YYYY-MM-DD" }
      - { name: heroImage, label: Hero image, widget: image, allow_multiple: false,media_folder: './'  }
      - { name: heroImageAltText, label: Hero image alt text }
      - { name: showHeadingPermalink, label: Show Permalinks in headings, widget: "boolean" }
      - { name: showToc, label: Show Table of contents, widget: "boolean" }
      - { name: author, label: Written by denio,benno,daniel or christoph?,  widget: "string" }
      - { name: tags, label: Tags one of "article" "music-production" "coding",  widget: "string" }
      - { name: published, label: Mark as published,  widget: "boolean" }

  - name: band-mates
    label: bandmates
    folder: src/content/band-mates
    create: true
    extension: md
    format: frontmatter
    preview_path: band-mates/{{id}}
    fields:
      - { name: name, label: Name, widget: "string" }
      - { name: nickName, label: Nickname, widget: "string" }
      - { name: postion, label: postion, widget: "string" }
      - { name: avatar, label: Avatar, widget: image, allow_multiple: false, media_folder: './'  }

  